apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: shipping-web-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shipping-web
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-web
spec:
  selector:
    app: shipping-web
  ports:
    - protocol: TCP
      port: 30010 # external port assigned to us
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shipping-web
  template:
    metadata:
      labels:
        app: shipping-web
    spec:
      containers:
        - name: shipping-web
          image: nislhin/ecamazon_shipping:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: "mongodb://shipping-mongo:27017/shipping_db"
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-mongo
spec:
  selector:
    app: shipping-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-mongo
  template:
    metadata:
      labels:
        app: shipping-mongo
    spec:
      containers:
        - name: shipping-mongo
          image: mongo
          ports:
            - containerPort: 27017
